name: Cypress Parallel Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    name: Cypress Test Suite
    runs-on: ubuntu-latest
    strategy:
      # When set to true, GitHub will cancel all in-progress jobs if any matrix job fails
      fail-fast: false
      matrix:
        # Split tests across multiple parallel instances
        containers: [1, 2, 3, 4]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          # Parallel runs and record the results
          record: true
          parallel: true
          group: "UI Tests"
          # Split tests between containers
          ci-build-id: ${{ github.run_id }}
        env:
          # Pass GitHub token and Cypress dashboard record key
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Set a unique build ID to identify the parallel builds
          CYPRESS_PARALLEL_ID: ${{ strategy.job-index }}
          # Configure where to save individual reports
          CYPRESS_MOCHAWESOME_REPORT_DIR: cypress/reports/mochawesome-report

      - name: Save test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report-${{ strategy.job-index }}
          path: cypress/reports
          retention-days: 5
          if-no-files-found: warn

  merge-reports:
    name: Merge Test Reports
    needs: cypress-run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: cypress-reports

      - name: Display structure of downloaded files
        run: ls -R cypress-reports

      - name: Merge reports
        run: |
          # Ensure the reports directory exists
          mkdir -p merged-reports

          # Install mochawesome-merge and mochawesome-report-generator
          npm install -g mochawesome-merge mochawesome-report-generator

          # Merge the JSON reports
          mochawesome-merge cypress-reports/cypress-report-*/mochawesome-report/*.json > merged-reports/merged.json

          # Generate HTML from the merged JSON
          marge merged-reports/merged.json -f report -o merged-reports

      - name: Upload merged report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-merged-report
          path: merged-reports
          retention-days: 30
